#include <mach/mach.h>
#include <stdbool.h>

// auto-generated by MIG (using xnu/osfmk/mach/task.defs):
//     mig \
//         -header task.h         \
//         -user task_user.c      \
//         -server task_server.c  \
//         -sheader task_server.h \
//          task.defs
//
typedef struct {
		mach_msg_header_t             Head;
		NDR_record_t                  NDR;
		task_flavor_t                 flavor;
		mach_msg_type_number_t        task_info_outCnt;
} __attribute__((packed, aligned(4))) ___Request__task_info_t;

typedef struct {
		mach_msg_header_t             Head;
		NDR_record_t                  NDR;
		kern_return_t                 RetCode;
		mach_msg_type_number_t        task_info_outCnt;
		integer_t                     task_info_out[94];
} __attribute__((packed, aligned(4))) ___Reply__task_info_t;

// found in osfmk/kdp/kdp_dyld.h
struct user64_dyld_all_image_infos {
	uint32_t                           version;
	uint32_t                           infoArrayCount;
	uint64_t                           infoArray;
	uint64_t                           notification;
	bool                               processDetachedFromSharedRegion;
	bool                               libSystemInitialized;
	uint64_t                           dyldImageLoadAddress;
	uint64_t                           jitInfo;
	uint64_t                           dyldVersion;
	uint64_t                           errorMessage;
	uint64_t                           terminationFlags;
	uint64_t                           coreSymbolicationShmPage;
	uint64_t                           systemOrderFlag;
	uint64_t                           uuidArrayCount; // dyld defines this as a uintptr_t despite it being a count
	uint64_t                           uuidArray;
	uint64_t                           dyldAllImageInfosAddress;
	/* the following field is only in version 10 (Mac OS X 10.7, iOS 4.2) and later */
	uint64_t                           initialImageCount;
	/* the following field is only in version 11 (Mac OS X 10.7, iOS 4.2) and later */
	uint64_t                           errorKind;
	uint64_t                           errorClientOfDylibPath;
	uint64_t                           errorTargetDylibPath;
	uint64_t                           errorSymbol;
	/* the following field is only in version 12 (Mac OS X 10.7, iOS 4.3) and later */
	uint64_t                           sharedCacheSlide;
	/* the following field is only in version 13 (Mac OS X 10.9, iOS 7.0) and later */
	uint8_t                            sharedCacheUUID[16];
	/* the following field is only in version 15 (macOS 10.12, iOS 10.0) and later */
	uint64_t                           sharedCacheBaseAddress;
	uint64_t                           timestamp;
	uint64_t                           dyldPath;
	mach_port_name_t                   notifyMachPorts[8];
	uint64_t                           reserved[9];
	/* the following fields are only in version 16 (macOS 10.13, iOS 12.0) and later */
	uint64_t                           compact_dyld_image_info_addr;
	uint64_t                           compact_dyld_image_info_size;
	uint32_t                           platform;
	/* the following fields are only in version 17 (macOS 10.16) and later */
	uint32_t                           aotInfoArrayCount;
	uint64_t                           aotInfoArray;
	uint64_t                           aotTimestamp;
};

// raw mach_task_self
__attribute((always_inline))
static inline mach_port_t
_mach_task_self(void)
{
#define MACH_TASK_SELF_TRAP (-28)
    register uint64_t x0  __asm__("x0");
    register uint64_t x16 __asm__("x16") = MACH_TASK_SELF_TRAP;

    __asm__ volatile (
        "svc #0x80"
        : "=r"(x0),
          "+r"(x16)
        :
        : "cc", "memory"
    );
    return (mach_port_t)x0;
}

// raw mach_msg2
__attribute((always_inline))
static inline kern_return_t
_mach_msg2(void                    *data,
           uint64_t                 options,
           mach_msg_bits_t          msgh_bits,
           mach_msg_size_t          send_size,
           mach_port_t              remote_port,
           mach_port_t              local_port,
           mach_port_t              voucher_port,
           mach_msg_id_t            msgh_id,
           uint32_t                 desc_count,
           mach_port_t              rcv_name,
           mach_msg_size_t          rcv_size,
           mach_msg_priority_t      priority,
           mach_msg_timeout_t       timeout)
{
#define MACH_MSG2_TRAP (-47)
    register uint64_t x0  __asm__("x0")  = (uintptr_t)data;
    register uint64_t x1  __asm__("x1")  = options;
    register uint64_t x2  __asm__("x2")  = (uint64_t)msgh_bits        | ((uint64_t)send_size           << 32);
    register uint64_t x3  __asm__("x3")  = (uint64_t)remote_port      | ((uint64_t)local_port          << 32);
    register uint64_t x4  __asm__("x4")  = (uint64_t)voucher_port     | ((uint64_t)(uint32_t)msgh_id   << 32);
    register uint64_t x5  __asm__("x5")  = (uint64_t)desc_count       | ((uint64_t)rcv_name            << 32);
    register uint64_t x6  __asm__("x6")  = (uint64_t)rcv_size         | ((uint64_t)(uint32_t)priority  << 32);
    register uint64_t x7  __asm__("x7")  = (uint64_t)timeout;
    register uint64_t x16 __asm__("x16") = MACH_MSG2_TRAP;
    __asm__ volatile (
        "svc #0x80"
        : "+r"(x0),
          "+r"(x1),
          "+r"(x2),
          "+r"(x3),
          "+r"(x4),
          "+r"(x5),
          "+r"(x6),
          "+r"(x7),
          "+r"(x16)
        :
        : "cc", "memory"
    );
    return (kern_return_t)x0;
}

// raw mach_reply_port
__attribute((always_inline))
static inline mach_port_t
_mach_reply_port(void)
{
#define MACH_REPLY_PORT_TRAP (-26)
    register uint64_t x0  __asm__("x0");
    register uint64_t x16 __asm__("x16") = MACH_REPLY_PORT_TRAP;
    __asm__ volatile (
        "svc #0x80"
        : "=r"(x0),
          "+r"(x16)
        :
        : "cc", "memory"
    );
    return (mach_port_t)x0;
}

// raw mach_port_mod_refs
__attribute((always_inline))
static inline kern_return_t
_mach_port_mod_refs(mach_port_t        target,
                    mach_port_t        name,
                    mach_port_right_t  right,
                    int32_t            delta)
{
#define MACH_PORT_MOD_REFS_TRAP (-31)
    register uint64_t x0  __asm__("x0")  = (uint64_t)target;
    register uint64_t x1  __asm__("x1")  = (uint64_t)name;
    register uint64_t x2  __asm__("x2")  = (uint64_t)right;
    register uint64_t x3  __asm__("x3")  = (uint64_t)(uint32_t)delta;   // avoid sign-extension of negative deltas
    register uint64_t x16 __asm__("x16") = MACH_PORT_MOD_REFS_TRAP;
    __asm__ volatile (
        "svc #0x80"
        : "+r"(x0),
          "+r"(x1),
          "+r"(x2),
          "+r"(x3),
          "+r"(x16)
        :
        : "cc", "memory"
    );
    return (kern_return_t)x0;
}

// this function does the same as a call to the library function
// task_info(mach_task_self, TASK_DYLD_INFO, ...)
__attribute__((weak))
bool dyld_all_image_infos_get(struct user64_dyld_all_image_infos *image_infos)  {
    task_t task = _mach_task_self();
    if (task == MACH_PORT_NULL) {
        return (false);
    }
    mach_port_t reply_port = _mach_reply_port();
    if (reply_port == MACH_PORT_NULL) {
        return (false);
    }

    struct msg_buffer {
        union {
            ___Request__task_info_t request;
            ___Reply__task_info_t   response;
        };
        mach_msg_max_trailer_t      trailer;
    };

    // subsystem task base = 3400 task_info is the 6th routine
    #define MIG_TASK_INFO_MSGH_ID 3405
    //__builtin_debugtrap();
    struct msg_buffer msg = {
        .request = {
            .Head = {
                .msgh_bits = MACH_MSGH_BITS(MACH_MSG_TYPE_COPY_SEND, MACH_MSG_TYPE_MAKE_SEND_ONCE),
                .msgh_size = sizeof(___Request__task_info_t),
                .msgh_remote_port = task,
                .msgh_local_port = reply_port,
                .msgh_voucher_port = 0,
                .msgh_id = MIG_TASK_INFO_MSGH_ID},
            .NDR = {
                .mig_vers = 0,
                .if_vers = 0,
                .reserved1 = 0,
                .mig_encoding = 0,
                .int_rep = 0,
                .char_rep = 0,
                .float_rep = 0,
                .reserved2 = 0,
            },
            .flavor = TASK_DYLD_INFO,
            .task_info_outCnt = TASK_DYLD_INFO_COUNT},
    };
    //__builtin_debugtrap();

#define MACH64_SEND_KOBJECT_CALL 0x200000000
    kern_return_t kr = _mach_msg2(
        &msg,
        MACH_SEND_MSG | MACH_RCV_MSG | MACH64_SEND_KOBJECT_CALL,
        MACH_MSG_TYPE_COPY_SEND | (MACH_MSG_TYPE_MAKE_SEND_ONCE << 8),
        sizeof(___Request__task_info_t),
        task,
        reply_port,
        MACH_PORT_NULL,
        MIG_TASK_INFO_MSGH_ID,
        0,
        reply_port,
        sizeof(___Reply__task_info_t) + MAX_TRAILER_SIZE,
        MACH_MSG_PRIORITY_UNSPECIFIED,
        MACH_MSG_TIMEOUT_NONE);

    if (kr != KERN_SUCCESS
        || msg.response.RetCode != KERN_SUCCESS
        || msg.response.task_info_outCnt != TASK_DYLD_INFO_COUNT) {
        (void)_mach_port_mod_refs(
            task,
            reply_port,
            MACH_PORT_RIGHT_RECEIVE,
            -1
        );
        return (false);
    }

    task_dyld_info_data_t dyld_info;
    __builtin_memcpy(
        &dyld_info,
        msg.response.task_info_out,
        sizeof(dyld_info)
    );

    __builtin_memcpy(
        image_infos,
        (void *)dyld_info.all_image_info_addr,
        sizeof(struct user64_dyld_all_image_infos)
    );

    (void)_mach_port_mod_refs(
        task,
        reply_port,
        MACH_PORT_RIGHT_RECEIVE,
        -1
    );

    return (true);
}

/*
#include <stdio.h>
#include <stdlib.h>

int main(void) {
    struct user64_dyld_all_image_infos image_infos;
    if (dyld_all_image_infos_get(&image_infos) == false) {
        (void)fprintf(stderr, "error\n");
        exit(1);
    }
    struct user64_dyld_all_image_infos *p = &image_infos;

    fprintf(stderr,
            "struct user64_dyld_all_image_infos @ %p {\n"
            "    version                          = %u\n"
            "    infoArrayCount                   = %u\n"
            "    infoArray                        = 0x%016llx\n"
            "    notification                     = 0x%016llx\n"
            "    processDetachedFromSharedRegion  = %s\n"
            "    libSystemInitialized             = %s\n"
            "    dyldImageLoadAddress             = 0x%016llx\n"
            "    jitInfo                          = 0x%016llx\n"
            "    dyldVersion                      = 0x%016llx\n"
            "    errorMessage                     = 0x%016llx\n"
            "    terminationFlags                 = 0x%016llx\n"
            "    coreSymbolicationShmPage         = 0x%016llx\n"
            "    systemOrderFlag                  = 0x%016llx\n"
            "    uuidArrayCount                   = %llu\n"
            "    uuidArray                        = 0x%016llx\n"
            "    dyldAllImageInfosAddress         = 0x%016llx\n"
            "    initialImageCount                = %llu\n"
            "    errorKind                        = %llu\n"
            "    errorClientOfDylibPath           = 0x%016llx\n"
            "    errorTargetDylibPath             = 0x%016llx\n"
            "    errorSymbol                      = 0x%016llx\n"
            "    sharedCacheSlide                 = 0x%016llx\n"
            "    sharedCacheUUID                  = %02x%02x%02x%02x-%02x%02x-%02x%02x-%02x%02x-%02x%02x%02x%02x%02x%02x\n"
            "    sharedCacheBaseAddress           = 0x%016llx\n"
            "    timestamp                        = %llu\n"
            "    dyldPath                         = 0x%016llx\n"
            "    notifyMachPorts                  = [ 0x%08x, 0x%08x, 0x%08x, 0x%08x, 0x%08x, 0x%08x, 0x%08x, 0x%08x ]\n"
            "    reserved                         = [ 0x%016llx, 0x%016llx, 0x%016llx, 0x%016llx, 0x%016llx, 0x%016llx, 0x%016llx, 0x%016llx, 0x%016llx ]\n"
            "    compact_dyld_image_info_addr     = 0x%016llx\n"
            "    compact_dyld_image_info_size     = 0x%016llx\n"
            "    platform                         = %u\n"
            "    aotInfoArrayCount                = %u\n"
            "    aotInfoArray                     = 0x%016llx\n"
            "    aotTimestamp                     = 0x%016llx\n"
            "}\n",
            (const void *)p,
            p->version,
            p->infoArrayCount,
            (unsigned long long)p->infoArray,
            (unsigned long long)p->notification,
            p->processDetachedFromSharedRegion ? "true" : "false",
            p->libSystemInitialized ? "true" : "false",
            (unsigned long long)p->dyldImageLoadAddress,
            (unsigned long long)p->jitInfo,
            (unsigned long long)p->dyldVersion,
            (unsigned long long)p->errorMessage,
            (unsigned long long)p->terminationFlags,
            (unsigned long long)p->coreSymbolicationShmPage,
            (unsigned long long)p->systemOrderFlag,
            (unsigned long long)p->uuidArrayCount,
            (unsigned long long)p->uuidArray,
            (unsigned long long)p->dyldAllImageInfosAddress,
            (unsigned long long)p->initialImageCount,
            (unsigned long long)p->errorKind,
            (unsigned long long)p->errorClientOfDylibPath,
            (unsigned long long)p->errorTargetDylibPath,
            (unsigned long long)p->errorSymbol,
            (unsigned long long)p->sharedCacheSlide,
            p->sharedCacheUUID[0], p->sharedCacheUUID[1], p->sharedCacheUUID[2], p->sharedCacheUUID[3],
            p->sharedCacheUUID[4], p->sharedCacheUUID[5],
            p->sharedCacheUUID[6], p->sharedCacheUUID[7],
            p->sharedCacheUUID[8], p->sharedCacheUUID[9],
            p->sharedCacheUUID[10], p->sharedCacheUUID[11], p->sharedCacheUUID[12],
            p->sharedCacheUUID[13], p->sharedCacheUUID[14], p->sharedCacheUUID[15],
            (unsigned long long)p->sharedCacheBaseAddress,
            (unsigned long long)p->timestamp,
            (unsigned long long)p->dyldPath,
            (unsigned)p->notifyMachPorts[0], (unsigned)p->notifyMachPorts[1],
            (unsigned)p->notifyMachPorts[2], (unsigned)p->notifyMachPorts[3],
            (unsigned)p->notifyMachPorts[4], (unsigned)p->notifyMachPorts[5],
            (unsigned)p->notifyMachPorts[6], (unsigned)p->notifyMachPorts[7],
            (unsigned long long)p->reserved[0], (unsigned long long)p->reserved[1],
            (unsigned long long)p->reserved[2], (unsigned long long)p->reserved[3],
            (unsigned long long)p->reserved[4], (unsigned long long)p->reserved[5],
            (unsigned long long)p->reserved[6], (unsigned long long)p->reserved[7],
            (unsigned long long)p->reserved[8],
            (unsigned long long)p->compact_dyld_image_info_addr,
            (unsigned long long)p->compact_dyld_image_info_size,
            p->platform,
            p->aotInfoArrayCount,
            (unsigned long long)p->aotInfoArray,
            (unsigned long long)p->aotTimestamp);

    return (EXIT_SUCCESS);
}
*/
