[package]
name = "dynld"
description = "An experimental OSX/iOS dynamic linker"
version = "0.0.1"
edition = "2024"
authors = ["Paul Ducos-Saksela"]
publish = false

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"


[dependencies]
scroll = { version = "0.13.0", default-features = false }
scroll_derive = "0.13.1"
