[package]
name = "dynld"
description = "An experimental OSX/iOS dynamic linker"
version = "0.0.1"
edition = "2024"
authors = ["Paul Ducos-Saksela"]
publish = false

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[workspace]
resolver = "2"
members = ["libs/*", "crates/*"]

[dependencies]
sys    = { path = "libs/sys" }
array  = { path = "libs/array" }
dynld-std = { path = "crates/dynld-std" }
dynld-core = { path = "crates/dynld-core" }
dynld-alloc = { path = "crates/dynld-alloc" }
