[package]
name = "dynld-core"
version = "0.0.1"
edition = "2024"

[dependencies]
array = { path = "../../libs/array" }
sys = { path = "../../libs/sys" }
jump   = { path = "../../libs/jump" }
container = { path = "../../libs/container" }
dynld-std = { path = "../dynld-std" }
scroll = { version = "0.13.0", default-features = false }
scroll_derive = "0.13.1"